CREATE TABLE IF NOT EXISTS `ClassifierWords` (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	Word CHAR(40) NOT NULL UNIQUE,
	Quality FLOAT NOT NULL DEFAULT 1,
	LastUpdated INT UNSIGNED NOT NULL DEFAULT 0,
	INDEX (Word),
	INDEX (LastUpdated),
	PRIMARY KEY (id)
) ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS `ClassifierClassSamples` (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	Class INT UNSIGNED NOT NULL UNIQUE,
	Frequency FLOAT NOT NULL,
	INDEX (Class),
	PRIMARY KEY (id)
) ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS `ClassifierFrequency` (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	Word INT UNSIGNED NOT NULL REFERENCES ClassifierWords(id),
	Class INT UNSIGNED NOT NULL,
	Frequency FLOAT NOT NULL,
	UNIQUE INDEX (Word,Class),
	INDEX (Word),
	INDEX (Class),
	PRIMARY KEY (id)
) ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS `ClassifierOrderFrequency` (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	Word INT UNSIGNED NOT NULL REFERENCES ClassifierWords(id),
	PrevWord INT UNSIGNED REFERENCES ClassifierWords(id),
	Class INT UNSIGNED NOT NULL,
	Frequency FLOAT NOT NULL,
	UNIQUE INDEX (Word,PrevWord,Class),
	INDEX (Word),
	INDEX (PrevWord),
	INDEX (Class),
	PRIMARY KEY (id)
) ENGINE = InnoDB;
